language: go

go: 1.1

install:
  - go get -d code.google.com/p/log4go
  - go get -d github.com/quarnster/parser
  - go get -d github.com/quarnster/util
  - go get -d github.com/howeyc/fsnotify
  - go get -d github.com/robmerrell/comandante
  - pwd
  - ls
  - ls ..
  - ls ../../
  - ls ../../../
  - ls ../../quarnster/
  - cd ../../quarnster/completion/build

script:
  - make
  - make test
