language: go

go: 1.1

install:
  - go get -d code.google.com/p/log4go
  - go get -d github.com/quarnster/parser
  - go get -d github.com/quarnster/util
  - go get -d github.com/howeyc/fsnotify
  - go get -d github.com/robmerrell/comandante
  - pwd
  - cd ..
  - mv completion ../quarnster/
  - ls ../quarnster/
  - cd ../quarnster/completion/
  - ls
  - ls ..
  - cd build

script:
  - make
  - make test
